blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new
    about: Suggest an idea for this project
  - name: I have a question or need support
    url: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/discussions/new
    about: Use Github Discussions to find support and ask general questions
