version: '3.1'

services:
  mqtt:
    container_name: mqtt
    env_file:       ./config.env
    image:   mqtt:local
    build:
      context: ./mqtt
    ports:
      - 1883:1883
      - 9001:9001

  mqtt-listener:
    image:          mqtt:local
    container_name: mqtt-listener
    command:        /listener-cmd.sh
    env_file:       ./config.env
    depends_on:
        - mqtt

  mqtt-dev-sensor:
    image:          mqtt:local
    container_name: mqtt-dev-sensor
    command:        /dev-sensor.sh
    env_file:       ./config.env
    depends_on:
        - mqtt

  mqtt-dev-binary-sensor:
    image:          mqtt:local
    container_name: mqtt-dev-binary-sensor
    command:        /dev-binary-sensor.sh
    env_file:       ./config.env
    depends_on:
        - mqtt

  node-red:
    container_name: node-red
    env_file:       ./config.env
    build:
      context: ./node-red
    command: npm run dev:watch
    volumes:
      - '..:/data-dev/node_modules/node-red-contrib-home-assistant'
    #   - './node-red/root-fs/data-dev/flows.json:/data-dev/flows.json'   # Map flows file for easy commitable examples building
    ports:
      - 1880:1880
      - 9123:9229

  home-assistant:
    container_name: home-assistant
    env_file:       ./config.env
    build:
      context: ./home-assistant
    # While messing with HA config map the repo config to the container for easy changes
    # volumes:
    #   - './home-assistant/root-fs/config/configuration.yaml:/config/configuration.yaml'
    ports:
      - 8300:8300
      - 8123:8123
    depends_on:
      - mqtt

